CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  uname VARCHAR NOT NULL,
  email VARCHAR UNIQUE NOT NULL,
  password VARCHAR NOT NULL,
  phone VARCHAR NOT NULL,
  created_at VARCHAR DEFAULT CURRENT_TIMESTAMP,
  updated_at VARCHAR DEFAULT CURRENT_TIMESTAMP
);