CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  password VARCHAR NOT NULL,
  created_at VARCHAR DEFAULT CURRENT_TIMESTAMP,
  updated_at VARCHAR DEFAULT CURRENT_TIMESTAMP
);