CREATE TABLE IF NOT EXISTS contact (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  email VARCHAR ,
  phone VARCHAR NOT NULL,
  message VARCHAR,
  created_at VARCHAR DEFAULT CURRENT_TIMESTAMP,
  updated_at VARCHAR DEFAULT CURRENT_TIMESTAMP,
  user_id BIGINT
);